import type {NextConfig} from "next";

const slugToCategory: Record<string, string> = {
    "personal-training-hannover-firmenfitness": "firmenfitness",
    "heise-testet-smarte-springseile-mit-tipps-von-personaltrainer-hannover": "news",
    "mental-coaching": "personal-training-coaching",
    "kinetisches-taping": "therapie-rehabilitation",
    "ernaehrungsberatung": "personal-training-coaching",
    "personal-training": "personal-training-coaching",
    "smart-ziele-setzen": "motivation",
    "lange-trainingseinheiten-behindern-den-muskelaufbau": "fitness",
    "arthrose": "gesundheit",
    "warum-du-ein-trainingstagebuch-fuehren-solltest": "fitness",
    "neue-kurse-starten-sie-durch": "fitness",
    "das-kleine-eiweisspulver-kompendium": "ernaehrung",
    "functional-movement-systems": "therapie-rehabilitation",
    "was-alkohol-mit-dir-macht": "gesundheit",
    "lws-rueckenschmerzen-bekaempfen": "gesundheit",
    "symmetrie-die-natuerliche-balance-des-koerpers": "fitness",
    "kompendium-iifym-suendigen-und-abnehmen": "ernaehrung",
    "nahrungsmittelindustrie": "ernaehrung",
    "tschuess-2018-hallo-2019": "motivation",
    "burpees": "fitness",
    "uebersaeuerung": "gesundheit",
    "wenn-du-angst-hast-etwas-falsch-zu-machen": "motivation",
    "die-groesste-luege-die-wir-immer-hoeren-und-erzaehlen": "motivation",
    "technik-kreuzheben-richtig-ausfuehren": "fitness",
    "faszien-und-wohlbefinden": "gesundheit",
    "salz-lebensnotwendig": "ernaehrung",
    "ist-krafttraining-fuer-stumpfe-pumper": "fitness",
    "vitamin-c": "gesundheit",
    "essen-und-sport": "fitness",
    "laufen-gesundheit": "fitness",
    "elsaesser-flammkuchen": "ernaehrung",
    "immunsystem-vitamin-c-und-zink": "gesundheit",
    "die-wahrheit-ueber-ballaststoffe": "ernaehrung",
    "avocado-thunfisch-creme": "ernaehrung",
    "beweglichkeit": "fitness",
    "workout-kurz-und-effektiv": "fitness",
    "5-grundregeln-fuer-anfaenger": "fitness",
    "msm": "ernaehrung",
    "3-simple-tipps-zum-abnehmen-3": "abnehmen",
    "2018-motiviert_ins_neue_jahr": "motivation",
    "eier": "ernaehrung",
    "auswirkungen-von-zucker-eine-legale-droge": "ernaehrung",
    "10-dinge-die-deinen-trainingsfortschritt-behindern": "fitness",
    "trinken-wasser-als-basis-unserer-gesundheit": "gesundheit",
    "wwofuer-kaempfst-du": "motivation",
    "der-koerper-im-dauertraining": "fitness",
    "basilikum-walnuss-coleslaw": "ernaehrung",
    "der-start-uebungen-erlernen": "fitness",
    "mindestkalorienbedarf": "ernaehrung",
    "seilspringen": "fitness",
    "spargel-sossen": "ernaehrung",
    "vorsatz-ziel-unterschied": "motivation",
    "paleo-ein-kurzer-ueberblick": "ernaehrung",
    "hitze-trinkverhalten": "gesundheit",
    "yoga-effektiv-in-kleingruppen": "fitness",
    "warum-du-eine-massephase-meiden-solltest": "fitness",
    "eine-uebung-verschiedene-trainingslevel": "fitness",
    "die-top-5-der-unbekannten-supplements": "ernaehrung",
    "sie-sind-was-sie-denken": "motivation",
    "outdoor-spass": "fitness",
    "training-mit-muskelkater": "fitness",
    "osteoporose": "gesundheit",
    "blog-zucker": "ernaehrung",
    "fit-in-den-fruehling": "fitness",
    "drei-einfache-schritte-zur-optimalen-ernaehrung": "ernaehrung",
    "ist-zu-viel-eiweiss-schaedlich": "ernaehrung",
    "die-mahlzeit-nach-dem-training-post-workout-meal": "ernaehrung",
    "schlaf-und-gesundheit": "gesundheit",
    "das-richtige-oel-zum-braten": "ernaehrung",
    "technik-bankdruecken-richtig-ausgefuehrt": "fitness",
    "10-gruende-warum-du-nicht-staerker-wirst": "fitness",
    "stress-serie-3-die-wichtigste-strategie-gegen-stress": "gesundheit",
    "luegen-koerperbautyp-und-stoffwechseltyp": "abnehmen",
    "outdoor-training": "fitness",
    "workout-2plus2-kurz-und-effektiv": "fitness",
    "problem-unpassendes-trainingsprogramm": "fitness",
    "nur-superhelden-tragen-handschuhe": "fitness",
    "die-anfaenge-im-fitnessstudio": "fitness",
    "3-strategien-zum-superhelden-koerper-durch-crossfit": "fitness",
    "wozu-kraftsport": "fitness",
    "der-mythos-von-sauberer-ernaehrung": "ernaehrung",
    "uebertraining-das-kleine-einmaleins": "fitness",
    "3-simple-tipps-zum-abnehmen-2": "abnehmen",
    "schilddruese": "gesundheit",
    "zink": "gesundheit",
    "workout-intensiv-effektiv-skalierbar": "fitness",
    "abnehmen-in-der-praxis": "abnehmen",
    "just-do-it-was-wir-daraus-lernen-koennen": "motivation",
    "suessungsmittel": "ernaehrung",
    "uebersaeuerung-gesichter": "gesundheit",
    "abnehmen-aber-wie": "abnehmen",
    "rezept-fitness-desserts": "ernaehrung",
    "abnehmen-und-ernaehrung-aber-wie": "abnehmen",
    "pyramiden": "fitness",
    "muskel-memory-effekt": "fitness",
    "7-cardio-alternativen-zum-joggen": "fitness",
    "schweinehund-als-trainingspartner": "fitness",
    "training-knappe-zeit": "fitness",
    "sinnvolles-schuhwerk": "gesundheit",
    "positiv-durch-den-tag": "motivation",
    "kraft-muskeln-stimmt-die-formel": "fitness",
    "zuckerreduzierte-ernaehrung": "ernaehrung",
    "rezept-pfannen-lachs-mit-basilikum": "ernaehrung",
    "das-herz-der-motor-des-menschen": "gesundheit",
    "keine-ausreden": "motivation",
    "achtung-verspannung": "gesundheit",
    "5-gruende-gegen-stimulanzien": "fitness",
    "fit-chicks-crossfit-und-die-realitaet": "fitness",
    "die-luege-des-gesundheitlichen-fortschritts": "gesundheit",
    "6-schlechte-uebungen-die-du-wirklich-meiden-solltest": "fitness",
    "was-lineare-progression-wirklich-ist": "fitness",
    "nicht-artgerechte-ernaehrung-ein-modernes-maerchen": "ernaehrung",
    "kurze-uebungen-fuer-zwischendurch": "fitness",
    "ernaehrung-der-quickstart-guide": "ernaehrung",
    "muskelform-veraendern-funktioniert-es": "fitness",
    "leichtes-hohlkreuz-ueben-ein-hohlkreuz-ist-gut": "fitness",
    "cardio-training-mit-skalierung": "fitness",
    "wichtigster-trick-zum-abnehmen-den-jeder-kennt-und-keiner-nutzt": "abnehmen",
    "7-denkfehler-die-dich-scheitern-lassen": "fitness",
    "rezept-gesunde-kekse": "ernaehrung",
    "5-supplements-die-ihr-geld-nicht-wert-sind": "ernaehrung",
    "von-routinen-und-ritualen": "fitness",
    "sitzen-ist-der-tod-5-uebungen-die-helfen-nur-5-minuten": "fitness",
    "warum-du-wahrscheinlich-mehr-protein-essen-solltest": "ernaehrung",
    "besiege-den-inneren-schweinehund-mit-wissenschaft": "motivation",
    "30-minuten-fuer-mehr-bewegungsqualitaet-aus-huefte-und-schulter-mobility-workout": "fitness",
    "leben-ohne-kohlenhydrate-die-low-carb-diaet-2": "ernaehrung",
    "der-fluch-der-trainingsbooster": "fitness",
    "warum-ein-schlechtes-workout-okay-ist-die-fuenfer-regel": "motivation",
    "reis-thunfisch-salat": "ernaehrung",
    "starting-strength-eine-starke-basis-schaffen": "fitness",
    "kokos-beere-shake-weightgainer": "ernaehrung",
    "3-simple-tipps-zum-abnehmen-4": "abnehmen",
    "der-beste-trainingsplan": "fitness",
    "ist-aspartam-gefaehrlich-der-kuenstliche-suessstoff-unter-der-lupe": "ernaehrung",
    "das-ei-und-das-cholesterin": "ernaehrung",
    "statussymbol-gesundheit": "gesundheit",
    "5-minuten-ein-simpler-trick-fuer-ein-besseres-leben": "fitness",
    "spontanitaet-fuer-mehr-bewegung-im-alltag": "fitness",
    "6-kritikpunkte-fuer-paleo-fanatiker": "ernaehrung",
    "ein-team-wir-fuer-sie": "fitness",
    "krafttraining-frauen": "fitness",
    "blitz-pizza-leckeres-und-einfaches-rezept": "ernaehrung",
    "stagnation-und-eingefahrenheit": "fitness",
    "uebertraining-oder-warum-dein-koerper-schlauer-ist-als-jeder-experte": "fitness",
    "motivationsfaktor-trainingspartner": "fitness",
    "vor-dem-training-richtig-aufwaermen": "fitness",
    "training-mit-leerem-magen-fuehrt-es-zu-muskelverlust": "fitness",
    "pt-navigation": "fitness",
    "gebackener-schafskaese-auf-gemuesebett": "ernaehrung",
    "tabata": "fitness",
    "brokkoli-suppe-mit-protein-einlage": "ernaehrung",
    "rezept-gurke-frischkaese-roellchen": "ernaehrung",
    "mix-it-vier-uebungen-unzaehlige-trainingsplaene": "fitness",
    "fruehstueck-ist-die-unwichtigste-mahlzeit-des-tages-oder": "ernaehrung",
    "sommerzeit-tipps-gegen-schwitzen": "gesundheit",
    "gesundheitsreport-2018": "gesundheit",
    "frohe-weihnachten": "news",
    "diaeten-und-der-jo-jo-effekt": "abnehmen",
    "stress-serie-2-ist-stress-nur-eingebildet": "gesundheit",
    "precision-nutrition-das-paleo-problem": "ernaehrung",
    "kontinuitaet-der-wichtigste-faktor": "fitness",
    "baukloetze-und-das-sinnvollste-training-fuer-die-kondition": "fitness",
    "hier-spielt-die-musik-10-tracks-fuer-ein-hartes-training": "fitness",
    "was-soll-ich-essen-wenn-ich-krank-bin-precision-nutrition": "ernaehrung",
    "autsch-der-ruecken": "gesundheit",
    "intervallfasten": "ernaehrung",
    "abnehmen-ohne-kalorienzaehlen": "abnehmen",
    "luegen-koerperbautyp-und-stoffwechseltyp-2": "fitness",
    "mamaworkout": "fitness",
    "einfach-ist-einfach-besser": "fitness",
    "vitamin-d-sonnenhormon": "gesundheit",
    "muskelverlust-nach-einer-trainingspause": "fitness",
    "training-im-lockdown": "fitness",
    "chili-con-quinoa-und-natuerlich-carne": "ernaehrung",
    "der-katabole-teufel-und-der-muskelverlust": "motivation",
    "bewegungsmuffel": "fitness",
    "rezept-spinatrolle-mit-gemuese-puten-fuellung": "ernaehrung",
    "die-schockierende-wahrheit-ueber-tracking-von-kalorien-training-und-schlafqualitaet": "ernaehrung",
    "rezept-protein-pancakes": "ernaehrung",
    "der-unterschied-ruckartige-und-explosive-ausfuehrung": "fitness",
    "der-ruecken-tipps-fuer-den-alltag": "gesundheit",
    "rezept-avocado-toast": "ernaehrung",
    "machst-du-diesen-enorm-frustrierenden-trainingsfehler": "fitness",
    "spaghetti-mit-schafskaese-und-frischen-tomaten": "ernaehrung",
    "eine-simple-denkweise-fuer-gesundheit-und-bedeutungsvolle-resultate": "gesundheit",
    "nudeln-mit-tomaten-schafskaese-sosse": "ernaehrung",
    "was-uns-kraftsport-lehrt": "fitness",
    "lokaler-fettabbau-warum-er-funktioniert": "abnehmen",
    "mythos-nach-18-uhr-nichts-mehr-essen-das-steckt-dahinter": "ernaehrung",
    "2019-ziele-vorsaetze": "motivation",
    "functional-training-ein-sinnloser-hype": "fitness",
    "3-simple-tipps-zum-abnehmen-1": "abnehmen",
    "limits": "motivation",
    "die-12-haeufigsten-sport-ausreden": "motivation",
    "schwere-knochen-und-genetische-ungerechtigkeit": "ernaehrung",
    "der-reiter-auf-dem-elefant": "news",
    "das-fundament-die-3-makronaehrstoffe": "ernaehrung",
    "ziele-richtig-formulieren-vorhaben-umsetzen": "abnehmen",
    "krafttraining-8-gruende-warum-es-keine-alternative-gibt": "fitness",
    "5-tipps-um-gesund-zu-bleiben": "gesundheit",
    "weihnachtsstrategie": "ernaehrung",
    "magnesium": "gesundheit",
    "range-of-motion": "fitness",
    "sau-stark-die-grunduebungen": "fitness",
    "mach-sport": "fitness",
    "ei-avocado-aufstrich": "ernaehrung",
    "stress-serie-1-leidest-du-unter-stress": "gesundheit",
    "gesundheit-heute-schon-an-morgen-denken": "gesundheit",
    "blutspende": "gesundheit",
    "personal-training-online": "fitness",
    "wirbelsaeule-mitte-unseres-koerpers": "gesundheit",
    "schlechtes-essen-5-beispiele-aus-deinem-alltag": "ernaehrung",
    "verspannungen-schulter-nacken-bereich": "gesundheit",
    "trainingsfrequenz-pro-woche": "fitness",
    "sinnvolles-schuhwerk-2": "ernaehrung",
    "ernaehrung-satt-statt-hunger": "ernaehrung",
    "krafttraining-zum-abnehmen": "fitness",
    "gnocchi-mit-italienischem-gemuese": "ernaehrung",
    "10-gruende-zum-abnehmen": "abnehmen",
    "stress-serie-4-6-tipps-gegen-stress": "gesundheit",
    "lebensmittel": "ernaehrung",
    "staerker-schneller-besser-das-fitnessstudio-als-labor": "fitness",
    "drehbuch": "motivation",
    "besiege-den-inneren-schweinehund-mit-wissenschaft-2": "ernaehrung",
    "taegliches-wiegen-taegliches-leiden": "abnehmen",
    "leben-ohne-kohlenhydrate-die-low-carb-diaet": "ernaehrung",
    "10-tipps-fuer-einen-erholsameren-schlaf": "gesundheit",
    "stark-schoen-schlau-durch-bananen-pancakes": "ernaehrung",
    "warum-koennen-proteinpulver-sinnvoll-sein": "ernaehrung",
    "gelenkschmerzen-beim-training": "fitness",
    "die-trainingsintensitaet-bis-zum-muskelversagen": "fitness",
    "die-ernaehrung-unterwegs": "ernaehrung",
    "gesundheit-eigenverantwortung": "gesundheit",
    "partysnacks": "ernaehrung",
    "sind-nahrungsergaenzungsmittel-noetig": "ernaehrung",
    "cardio-workout": "fitness",
    "der-alltag-eines-fitnessshop-verkaeufers": "fitness",
    "gewaltpraevention": "news",
    "weihnachtsvorbereitung-krafttraining": "fitness",
    "valsalva-manoever-die-richtige-atmung-beim-training": "fitness",
    "fitness-trends-und-neue-produkte": "fitness",
    "corona": "gesundheit",
    "proteinreicher-snack-lecker-schnell-und-guenstig": "ernaehrung",
    "toedliche-mikrowelle-7-wahrheiten-ueber-das-strahlende-medium": "gesundheit",
    "teamgeist-online-training": "fitness",
    "3-1-fakten-ueber-nahrungsergaenzungsmittel": "ernaehrung",
    "eigenen-trainingsplan-erstellen": "fitness",
    "faszien-ein-ueberblick": "gesundheit",
    "stress-serie-5-6-weitere-tipps-gegen-stress": "gesundheit",
    "3-gruende-warum-kalorien-zaehlen-zeitverschwendung-ist": "ernaehrung",
    "technik-kniebeuge-richtig-ausfuehren": "fitness",
    "ist-ein-ernaehrungsplan-sinnvoll": "ernaehrung",
    "kurs-20190319": "news",
    "neues-kursangebot-ab-2020": "news",
    "goenne-deinem-nacken-und-ruecken-eine-auszeit": "news",
    "schmerztherapie": "therapie-rehabilitation",
    "medical-flossing": "therapie-rehabilitation",
    "abnehmen-mit-spass-februar": "news",
    "steak-mit-salat-und-chimichurri-sosse": "ernaehrung",
    "kettlebell-eine-kugel-die-es-in-sich-hat": "fitness",
    "muskelkater-muskelaufbau": "fitness",
    "das-saettigungsgefuehl-siegreich-gegen-den-hunger": "ernaehrung",
    "speiseoele-welches-soll-ich-nehmen": "ernaehrung",
    "kuenstliche-intelligenz-im-fitness": "fitness",
    "februar-aktion-bring-a-friend": "news",
    "wir-suchen-verstaerkung": "news",
    "neue-webseite": "news",
    "hygienekonzept": "news",
    "mamaworkout-20190424": "news",
    "personal-training-hannover-reha-sport-training": "therapie-rehabilitation",
    "koerperanalyse": "personal-training-coaching",
    "joggen-fuers-abnehmen-nee-lass-mal": "abnehmen",
    "koerperkomposition-die-lehre-von-fett-und-muskeln": "fitness"
};

const serviceRedirects = [
    {
        source: '/portfolio-items/personal-training-hannover-firmenfitness/:path*',
        destination: '/service/firmenfitness/personal-training-hannover-firmenfitness',
        permanent: true,
    },
    {
        source: '/portfolio-items/personal-training-hannover-reha-sport-training/:path*',
        destination: '/service/therapie-rehabilitation/personal-training-hannover-reha-sport-training',
        permanent: true,
    },
    {
        source: '/fitness-coaching/:path*',
        destination: '/service/personal-training-coaching',
        permanent: true,
    },
    {
        source: '/leistungen/:path*',
        destination: '/service',
        permanent: true,
    },
    {
        source: '/messen-therapieren/:path*',
        destination: '/service/therapie-rehabilitation',
        permanent: true,
    },
    {
        source: '/portfolio-items/schmerztherapie/:path*',
        destination: '/service/therapie-rehabilitation/schmerztherapie',
        permanent: true,
    },
    {
        source: '/portfolio-items/ernaehrungsberatung/:path*',
        destination: '/service/personal-training-coaching/ernaehrungsberatung',
        permanent: true,
    },
    {
        source: '/portfolio-items/koerperanalyse/:path*',
        destination: '/service/personal-training-coaching/koerperanalyse',
        permanent: true,
    },
    {
        source: '/portfolio-items/medical-flossing/:path*',
        destination: '/service/therapie-rehabilitation/medical-flossing',
        permanent: true,
    },
    {
        source: '/portfolio-items/functional-movement-systems/:path*',
        destination: '/service/therapie-rehabilitation/functional-movement-systems',
        permanent: true,
    },
    {
        source: '/portfolio-items/kinetisches-taping/:path*',
        destination: '/service/therapie-rehabilitation/kinetisches-taping',
        permanent: true,
    },
    {
        source: '/gruppenfitness/:path*',
        destination: '/service',
        permanent: true,
    },
    {
        source: '/varianten/:path*',
        destination: '/service',
        permanent: true,
    },
    {
        source: '/news/:path*',
        destination: '/blog/news',
        permanent: true,
    },
    {
        source: '/category/gesundheit/:path*',
        destination: '/blog/gesundheit',
        permanent: true,
    },
    {
        source: '/category/abnehmen/:path*',
        destination: '/blog/abnehmen',
        permanent: true,
    },
    {
        source: '/category/motivation/:path*',
        destination: '/blog/motivation',
        permanent: true,
    },
    {
        source: '/category/training/:path*',
        destination: '/blog/fitness',
        permanent: true,
    },
    {
        source: '/category/ernaehrung/:path*',
        destination: '/blog/ernaehrung',
        permanent: true,
    },
    {
        source: '/team2/:path*',
        destination: '/',
        permanent: true,
    },
    {
        source: '/contact-us/:path*',
        destination: '/#contact',
        permanent: true,
    },
    // Alles mit "personal-training" in der Portfolio-URL auf die Kategorie weiterleiten
    {
        source: '/portfolio-items/:slug(.*personal-training.*)',
        destination: '/service/personal-training-coaching',
        permanent: true,
    },
    // weitere Service-Redirects hier…
];

const isProd = process.env.NODE_ENV === 'production';

const nextConfig: NextConfig = {
    images: {
        remotePatterns: [
            isProd
                ? {
                    protocol: "https",
                    hostname: "api.personaltrainer-hannover.de",
                    pathname: "/uploads/**",
                }
                : {
                    protocol: "http",
                    hostname: "192.168.178.100",
                    port: "1337",
                    pathname: "/uploads/**",
                }
        ],
    },
    async redirects() {
        const blogRedirects = Object.entries(slugToCategory).map(([slug, categorySlug]) => ({
            source: `/${slug}`,
            destination: `/blog/${categorySlug}/${slug}`,
            permanent: true,
        }));

        return [
            // Statische Seiten

            // Dynamische Blog-Redirects
            ...blogRedirects,

            // Manuelle Service Redirects
            ...serviceRedirects,
        ];
    },
};

export default nextConfig;
